import "./global.sass";
import styles from "@/styles/Home.module.scss";

export const metadata = {
  title: "موجودی انبار",
  icons: {
    icon: "https://creazilla-store.fra1.digitaloceanspaces.com/cliparts/36190/coffee-logo-clipart-md.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <div className={styles.container}>{children}</div>
      </body>
    </html>
  );
}
